name: Every 30 minutes Job
on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30mins
  workflow_dispatch:     # Manual trigger option

concurrency:
  group: ${{ github.workflow }}  # 👈 Ensures uniqueness automatically
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          ONE_HOUR_BP_LONG_WEBHOOK: ${{ secrets.ONE_HOUR_BP_LONG_WEBHOOK }}
          ONE_HOUR_BP_SHORT_WEBHOOK: ${{ secrets.ONE_HOUR_BP_SHORT_WEBHOOK }}
          FOUR_HOUR_BP_LONG_WEBHOOK: ${{ secrets.FOUR_HOUR_BP_LONG_WEBHOOK }}
          FOUR_HOUR_BP_SHORT_WEBHOOK: ${{ secrets.FOUR_HOUR_BP_SHORT_WEBHOOK }}
        run: python 1hr_4hr.py
